import type { Metadata } from "next";
import localFont from "next/font/local";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import Nav from "@/components/nav";
import Footer from "@/components/footer";

const dm_sans = DM_Sans({
	subsets: ["latin"],
	variable: "--font-dm_sans",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${dm_sans.variable} antialiased font-DMSans`}>
				<Nav />
				{children}
				<Footer />
			</body>
		</html>
	);
}
